
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 90546
 */
public class Student_Panel extends javax.swing.JFrame {
           java.sql.PreparedStatement ps=null;
           java.sql.ResultSet rs=null;
           Statement stmt=null;
           Connection conn=Dbkatmanin.baglan();


    /**
     * Creates new form Student_Panel
     */
    public Student_Panel() {
        initComponents();
        this.setLocationRelativeTo(null);
        showGradeS();
        showAnoncement();
        SLecturesSelect();
    }
    
        private void SLecturesSelect(){
        try{ 

            String sql = "SELECT NAME FROM lesson ";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            ChoseLesson.removeAllItems();
            while (rs.next()){

                String dname = rs.getString("NAME");
                ChoseLesson.addItem(dname);

            }
        }        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
       

            public void showGradeS(){
        try {
            stmt = conn.createStatement();
            String query = "SELECT lesson.ID,lesson.NAME,lesson_code,student_info.NAME, student_info.SURNAME,student_info.USERNAME, MIDTERM, FINAL,AVERAGE,LETTER_GRADE FROM GRADE, LESSON, student_info WHERE GRADEL_ID = LESSON.ID AND GRADES_ID=student_info.ID " ;
            rs = stmt.executeQuery(query);
            SGradeshow.setModel(DbUtils.resultSetToTableModel(rs));
             }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }


    }
             public void showAnoncement(){
        try {
            stmt = conn.createStatement();
            String query = "SELECT NAME,SURNAME,ANNOUNCEMENT,DATE FROM teachers_info,announcement WHERE teachers_info.ID=AnnouncementT_ID " ;
            rs = stmt.executeQuery(query);
            SAnoncement.setModel(DbUtils.resultSetToTableModel(rs));
             }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }


    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Anoncement = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        SGradeshow = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        SAnoncement = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        ChoseLesson = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        AddLesson = new javax.swing.JButton();
        StudentIDP = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SGradeshow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SGradeshow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SGradeshowMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SGradeshow);

        Anoncement.addTab("Grades", jScrollPane1);

        SAnoncement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(SAnoncement);

        Anoncement.addTab("Anoncement", jScrollPane2);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("STUDENT PANEL");

        jLabel1.setText("Choose Lesson");

        jButton1.setText("Delete lesson");

        AddLesson.setText("Add lesson");
        AddLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLessonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StudentIDP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ChoseLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(AddLesson, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addComponent(Anoncement, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Anoncement, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(StudentIDP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChoseLesson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddLesson)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(145, 145, 145))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLessonActionPerformed
        // TODO add your handling code here:
               
            String stdID=StudentIDP.getText();
            String stdlessonbox = (String) ChoseLesson.getSelectedItem();
            String registerUserQuery = "INSERT INTO students_lesson (`ID`, `SLS_ID`, `SLL_ID`)  VALUES(NULL,?,?), grade (`ID`, `MIDTERM`, `FINAL`, `AVERAGE`, `LETTER_GRADE`, `GRADEL_ID`, `GRADES_ID`) VALUES(NULL,NULL,NULL,NULL,NULL,?,?) WHERE sls_id='"+stdID+"' ";
                 
            try {   
                    
                     ps=conn.prepareStatement(registerUserQuery);
                     ps.setString(2, stdlessonbox);
                     JOptionPane.showMessageDialog(null, "Lesson has added!!");
                 }
                 catch(SQLException ex){
                     Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
                 }
            showGradeS();
    }//GEN-LAST:event_AddLessonActionPerformed

    private void SGradeshowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SGradeshowMouseClicked
        // TODO add your handling code here:
        int i=SGradeshow.getSelectedRow();
        TableModel model = SGradeshow.getModel();  
        ChoseLesson.setSelectedItem(model.getValueAt(i,1).toString());
    }//GEN-LAST:event_SGradeshowMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLesson;
    private javax.swing.JTabbedPane Anoncement;
    private javax.swing.JComboBox<String> ChoseLesson;
    private javax.swing.JTable SAnoncement;
    private javax.swing.JTable SGradeshow;
    private javax.swing.JTextField StudentIDP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
