
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.PreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 90546
 */
public class Student_Signup1 extends javax.swing.JFrame {
    java.sql.PreparedStatement ps=null;
    java.sql.ResultSet rs=null;
    Connection conn=Dbkatmanin.baglan();

    /**
     * Creates new form Student_Signup1
     */
    public Student_Signup1() {
        initComponents();
        this.setLocationRelativeTo(null);

        ButtonGroup bg = new ButtonGroup();
        bg.add(sgenderm);
        bg.add(sgenderf);
        facultySelect();
        departmentSelect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        sgenderf = new javax.swing.JRadioButton();
        sfaculty = new javax.swing.JComboBox<>();
        sgenderm = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        sname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ssurname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        susername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        smnumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        sdepartment = new javax.swing.JComboBox<>();
        sdate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Sregister = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Faculty");

        sgenderf.setText("Famale");
        sgenderf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgenderfActionPerformed(evt);
            }
        });

        sfaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sfacultyActionPerformed(evt);
            }
        });

        sgenderm.setSelected(true);
        sgenderm.setText("Male");
        sgenderm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sgendermActionPerformed(evt);
            }
        });

        jLabel9.setText("Gender");

        jLabel1.setText("Name");

        ssurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssurnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Surname");

        jLabel3.setText("Username");

        jLabel4.setText("Password");

        jLabel5.setText("Date Of Birth");

        smnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnumberActionPerformed(evt);
            }
        });
        smnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                smnumberKeyTyped(evt);
            }
        });

        jLabel6.setText("Mobile Number");

        sdepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdepartmentActionPerformed(evt);
            }
        });

        jLabel7.setText("Department");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Back");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        Sregister.setText("REGISTER");
        Sregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(16, 16, 16)
                                        .addComponent(smnumber))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(sgenderm)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(sgenderf))
                                            .addComponent(susername)
                                            .addComponent(ssurname)
                                            .addComponent(sname)
                                            .addComponent(spassword)
                                            .addComponent(sfaculty, 0, 114, Short.MAX_VALUE)
                                            .addComponent(sdepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sdate, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Sregister))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ssurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(susername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sgenderm)
                    .addComponent(sgenderf))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(sfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sregister))
                .addGap(4, 4, 4)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ssurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssurnameActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        giris click_back = new giris();
        click_back.setVisible(true);
        click_back.pack();
        click_back.setLocationRelativeTo(null);
        click_back.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void sdepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sdepartmentActionPerformed

    private void smnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_smnumberActionPerformed

    private void smnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_smnumberKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();}
    }//GEN-LAST:event_smnumberKeyTyped

    private void sgendermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgendermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgendermActionPerformed

    private void SregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SregisterActionPerformed
        // TODO add your handling code here:
        String dname=sname.getText();
        String dsurname=ssurname.getText();
        String dusername=susername.getText();
        String dpassword=String.valueOf(spassword.getPassword());
        String ddate=sdate.getText();
        String dmnumber=smnumber.getText();
        String stddepartment = (String) sdepartment.getSelectedItem();
        String stdfaculty = (String) sfaculty.getSelectedItem();
        
        String dgender = "Male";
         
         if(sgenderf.isSelected()){
             dgender = "Female";
         }
         
          if(verifyFields())
         {
// check if the username already exists
             if(!checkUsername(dusername))
             {
                 String registerUserQuery = "INSERT INTO student_wait (USERNAME, NAME, SURNAME, PASSWORD, MNUMBER, DEPARTMENT, FACULTY, GENDER, DATE) \n"+"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                 try {
                     ps=conn.prepareStatement(registerUserQuery);
                     ps.setString(1, dusername);
                     ps.setString(2, dname);
                     ps.setString(3, dsurname);
                     ps.setString(4, dpassword);
                     ps.setString(5, dmnumber);
                     ps.setString(6, stddepartment);
                     ps.setString(7, stdfaculty);
                     ps.setString(8, dgender);
                     ps.setString(9, ddate);
                     try{
                          if(ps.executeUpdate()!=0)
                         {
                             JOptionPane.showMessageDialog(null, " Your Account Has Been Created!!");
                         }
                          else{
                             JOptionPane.showMessageDialog(null, "Error Check your information!!");
                         }
                     }
                     catch(SQLException ex){
                         Logger.getLogger(Student_Signup1.class.getName()).log(Level.SEVERE, null, ex);
                      
                     }
                     
                     
                 }
                 catch(SQLException ex){
                     Logger.getLogger(Student_Signup1.class.getName()).log(Level.SEVERE, null, ex);
                     
                 }
                 }
             
                 
         }
        
    }//GEN-LAST:event_SregisterActionPerformed

    private void sfacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sfacultyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sfacultyActionPerformed

    private void sgenderfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sgenderfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sgenderfActionPerformed

    /**
     * @param args the command line arguments
     * 
     */
    public boolean verifyFields(){
        String dname=sname.getText();
        String dsurname=ssurname.getText();
        String dusername=susername.getText();
        String dpassword=String.valueOf(spassword.getPassword());
        String ddate=sdate.getText();
        String dmnumber=smnumber.getText();
        if (dname.trim().equals("")||dsurname.trim().equals("")||dusername.trim().equals("")||dpassword.trim().equals("")||ddate.trim().equals("")||dmnumber.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Some Fields are Empty");
            return false;
        }
        else{
            return true;
        }
        
    }
    
     private void facultySelect(){
        try{ 
            String sql = "SELECT * FROM faculty";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();

            while (rs.next()){
                String name = rs.getString("Faculty_NAME");
                sfaculty.addItem(name);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void departmentSelect(){
        try{ 

            String sql = "SELECT * FROM department,faculty WHERE Faculty_NAME='"+sfaculty.getSelectedItem()+"'";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            sdepartment.removeAllItems();
            while (rs.next()){

                String dname = rs.getString("Department_NAME");
                sdepartment.addItem(dname);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public boolean checkUsername(String username){
        
        boolean username_exist=false;
        String query="SELECT * FROM STUDENT_WAIT WHERE username=?";
        try{
            ps=conn.prepareStatement(query);
            ps.setString(1,username); 
            rs=ps.executeQuery();
            if(rs.next()){
                username_exist=true;
                JOptionPane.showMessageDialog(null, "This Username is Already", "Username error!!", 2);
            }
 
        }
        catch(SQLException ex){
            Logger.getLogger(Student_Signup1.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
       
            
            
            
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Signup1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Signup1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sregister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField sdate;
    private javax.swing.JComboBox<String> sdepartment;
    private javax.swing.JComboBox<String> sfaculty;
    private javax.swing.JRadioButton sgenderf;
    private javax.swing.JRadioButton sgenderm;
    private javax.swing.JTextField smnumber;
    private javax.swing.JTextField sname;
    private javax.swing.JPasswordField spassword;
    private javax.swing.JTextField ssurname;
    private javax.swing.JTextField susername;
    // End of variables declaration//GEN-END:variables


}
