/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.sql.ResultSetMetaData;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author 90546
 */



public class Teachers_Panel extends javax.swing.JFrame {
           java.sql.PreparedStatement ps=null;
           java.sql.ResultSet rs=null;
           Statement stmt=null;
           Connection conn=Dbkatmanin.baglan();
           
           
        public Teachers_Panel() {
            
        initComponents();
        this.setLocationRelativeTo(null);
        ButtonGroup bg = new ButtonGroup();
        bg.add(sgenderm);
        bg.add(sgenderf);
        showBekleyen();
        showSet();
        showLecture();
        facultySelect();
        departmentSelect();
        showGrade();
        LectureSelect();
        
    }
    
        public void showSearch(){
        try {
            stmt = conn.createStatement();
            String SerchUsername=String.valueOf(Tsetusername.getText());
            String query = "SELECT * FROM student_info WHERE USERNAME='"+SerchUsername+"'" ;
            rs = stmt.executeQuery(query);
            Studentsettable.setModel(DbUtils.resultSetToTableModel(rs));
             }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }


    }
        public void showBekleyen(){
            try{
                stmt=conn.createStatement();
                String sql="SELECT * FROM student_wait ";
                ResultSet res=stmt.executeQuery(sql);

                StudentWaiting.setModel(DbUtils.resultSetToTableModel(res));
                
                
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                
            }
            
        }
        
        
        public void showGrade(){
        try {
            stmt = conn.createStatement();
            String query = "SELECT lesson.ID,lesson.NAME,student_info.ID,student_info.NAME, student_info.SURNAME,student_info.USERNAME, MIDTERM, FINAL,AVERAGE,LETTER_GRADE FROM GRADE, LESSON, student_info WHERE GRADEL_ID = LESSON.ID AND GRADES_ID=student_info.ID " ;
            rs = stmt.executeQuery(query);
            TGrade.setModel(DbUtils.resultSetToTableModel(rs));
             }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
         }


    }
                public void showLecture(){
            try{
                stmt=conn.createStatement();
               // String sql="SELECT * FROM lesson ";
                String query = "SELECT LESSON.ID, NAME, LESSON_CODE, LESSON_CREDI,LESSOND_ID, DEPARTMENT_NAME,FACULTY_NAME FROM LESSON, DEPARTMENT,FACULTY WHERE LESSOND_ID= DEPARTMENT.ID AND DEPARTMENTF_ID=FACULTY.ID " ;
                ResultSet res=stmt.executeQuery(query);

                TSlessonTable.setModel(DbUtils.resultSetToTableModel(res));
                
                
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                
            }
            
        }
          public void showSet(){
            try{
                stmt=conn.createStatement();
                String sql="SELECT * FROM student_info ";
                ResultSet res=stmt.executeQuery(sql);

                
                Studentsettable.setModel(DbUtils.resultSetToTableModel(res));
                
                
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                
            }
            
        }
    



   
    
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Studentset = new javax.swing.JTabbedPane();
        StudentSet = new javax.swing.JPanel();
        Tsupdate = new javax.swing.JButton();
        Tssearch = new javax.swing.JButton();
        Sadd = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        Studentsettable = new javax.swing.JTable();
        Tsetmnumber = new javax.swing.JTextField();
        Tsetusername = new javax.swing.JTextField();
        Tsetsurname = new javax.swing.JTextField();
        Tsetname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sFacultycombo = new javax.swing.JLabel();
        Sdeparrtmentcombo = new javax.swing.JComboBox<>();
        Sfacultycombo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        sgenderm = new javax.swing.JRadioButton();
        sgenderf = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        Tspassword = new javax.swing.JPasswordField();
        sdate = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Refresh_data = new javax.swing.JToggleButton();
        Tsdelete = new javax.swing.JToggleButton();
        Anouncement = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        AddLeccture = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        TSlessonTable = new javax.swing.JTable();
        TSDepartmentcombo = new javax.swing.JComboBox<>();
        TSLFaculty = new javax.swing.JComboBox<>();
        TSLName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TSCode = new javax.swing.JTextField();
        TSLessonID = new javax.swing.JTextField();
        TSLCredibox = new javax.swing.JTextField();
        TLessonSpecialID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LecUpdate = new javax.swing.JButton();
        TlessonsDelete = new javax.swing.JButton();
        Refresh_data1 = new javax.swing.JToggleButton();
        TeacherID_less = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        sdeletesignup = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        StudentWaiting = new javax.swing.JTable();
        TSwaitdelusername = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TGrade = new javax.swing.JTable();
        Midtermbox = new javax.swing.JTextField();
        Finalbox = new javax.swing.JTextField();
        TGfaculty = new javax.swing.JComboBox<>();
        Tgdepartment = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LectureGrade = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        TGID = new javax.swing.JTextField();
        Tgusername = new javax.swing.JTextField();
        Tgname = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(255, 51, 51));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Teacher Manage Page");

        Tsupdate.setText("Update");
        Tsupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsupdateActionPerformed(evt);
            }
        });

        Tssearch.setText("Search");
        Tssearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TssearchActionPerformed(evt);
            }
        });

        Sadd.setText("Add");
        Sadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaddActionPerformed(evt);
            }
        });

        Studentsettable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Surname", "Username", "Mobile Number", "Faculty", "Department"
            }
        ));
        Studentsettable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentsettableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(Studentsettable);

        Tsetname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsetnameActionPerformed(evt);
            }
        });

        jLabel6.setText("Mobile Number");

        jLabel7.setText("Username");

        jLabel8.setText("surname");

        jLabel9.setText("Name");

        jLabel10.setText("Department");

        sFacultycombo.setText("Faculty");

        Sfacultycombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SfacultycomboİtemStateChanged(evt);
            }
        });

        jLabel17.setText("Password");

        sgenderm.setSelected(true);
        sgenderm.setText("Male");

        sgenderf.setText("Famale");

        jLabel18.setText("Gender");

        sdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdateActionPerformed(evt);
            }
        });

        jLabel19.setText("Date");

        Refresh_data.setText("Refresh Data");
        Refresh_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_dataActionPerformed(evt);
            }
        });

        Tsdelete.setText("Delete");
        Tsdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsdeleteActionPerformed(evt);
            }
        });

        Anouncement.setText("Anouncement");
        Anouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnouncementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StudentSetLayout = new javax.swing.GroupLayout(StudentSet);
        StudentSet.setLayout(StudentSetLayout);
        StudentSetLayout.setHorizontalGroup(
            StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSetLayout.createSequentialGroup()
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentSetLayout.createSequentialGroup()
                        .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(StudentSetLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(Tsetname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentSetLayout.createSequentialGroup()
                                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sFacultycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(89, 89, 89)
                                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tsetsurname, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tsetusername, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tsetmnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sfacultycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sdeparrtmentcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Tspassword, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(StudentSetLayout.createSequentialGroup()
                                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentSetLayout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(Sadd, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentSetLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tssearch)
                                    .addComponent(Refresh_data))
                                .addGap(18, 18, 18)
                                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Anouncement)
                                    .addGroup(StudentSetLayout.createSequentialGroup()
                                        .addComponent(Tsupdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Tsdelete)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                    .addGroup(StudentSetLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sgenderm)
                        .addGap(28, 28, 28)
                        .addComponent(sgenderf)
                        .addGap(47, 47, 47)))
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        StudentSetLayout.setVerticalGroup(
            StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentSetLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(Tsetname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tsetsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tsetusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tsetmnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tspassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sfacultycombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sFacultycombo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sdeparrtmentcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sgenderm)
                    .addComponent(sgenderf)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(41, 41, 41)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tssearch)
                    .addComponent(Sadd)
                    .addComponent(Tsupdate)
                    .addComponent(Tsdelete))
                .addGap(42, 42, 42)
                .addGroup(StudentSetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anouncement)
                    .addComponent(Refresh_data))
                .addGap(44, 44, 44))
            .addComponent(jScrollPane7)
        );

        Studentset.addTab("Student Settings", StudentSet);

        AddLeccture.setText("Add Lecture");
        AddLeccture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLecctureActionPerformed(evt);
            }
        });

        TSlessonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Department", "Faculty", "Lecture"
            }
        ));
        TSlessonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TSlessonTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TSlessonTable);

        jLabel2.setText("Department");

        jLabel3.setText("Faculty");

        jLabel4.setText("Lecture Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Lecture");

        jLabel20.setText("Lessons of Credi");

        jLabel21.setText("Lesson of Code");

        TSCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSCodeActionPerformed(evt);
            }
        });

        TSLessonID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSLessonIDActionPerformed(evt);
            }
        });

        jLabel22.setText("Lecture ID");

        jLabel23.setText("Lesson Department ID");

        LecUpdate.setText("Update");
        LecUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecUpdateActionPerformed(evt);
            }
        });

        TlessonsDelete.setText("Delete");
        TlessonsDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TlessonsDeleteActionPerformed(evt);
            }
        });

        Refresh_data1.setText("Refresh Data");
        Refresh_data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_data1ActionPerformed(evt);
            }
        });

        jLabel27.setText("Teacher ID: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TSLName)
                                            .addComponent(TLessonSpecialID)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(TSLFaculty, 0, 96, Short.MAX_VALUE))
                                            .addComponent(TSDepartmentcombo, 0, 97, Short.MAX_VALUE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TeacherID_less, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(TSCode)
                                            .addComponent(TSLessonID)
                                            .addComponent(TSLCredibox, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addGap(70, 70, 70))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Refresh_data1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TlessonsDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LecUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddLeccture, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane6)
                .addGap(27, 27, 27))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSLFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSDepartmentcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(TLessonSpecialID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TSLCredibox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TSCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TSLessonID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TeacherID_less, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(29, 29, 29)
                .addComponent(AddLeccture)
                .addGap(18, 18, 18)
                .addComponent(LecUpdate)
                .addGap(18, 18, 18)
                .addComponent(TlessonsDelete)
                .addGap(18, 18, 18)
                .addComponent(Refresh_data1)
                .addGap(61, 61, 61))
        );

        Studentset.addTab("Lessons", jPanel4);

        jButton1.setText("Add Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        sdeletesignup.setText("Delete Signup");
        sdeletesignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sdeletesignupActionPerformed(evt);
            }
        });

        StudentWaiting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        StudentWaiting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentWaitingMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(StudentWaiting);

        jLabel11.setText("Add or Deleting by Username:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TSwaitdelusername, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sdeletesignup)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1247, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(sdeletesignup)
                        .addComponent(TSwaitdelusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))))
        );

        Studentset.addTab("Student Confirm", jPanel2);

        TGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TGrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TGradeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TGrade);

        jLabel12.setText("Faculty");

        jLabel13.setText("Department");

        jLabel14.setText("Lecture");

        jLabel15.setText("Midterm");

        jLabel16.setText("Final");

        jLabel24.setText("Student ID:");

        jLabel25.setText("Student USERNAME: ");

        jLabel26.setText("Student Name: ");

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(0, 42, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Midtermbox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Finalbox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(LectureGrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addComponent(TGID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tgusername, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Tgname)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Tgdepartment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(TGfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TGfaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tgdepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LectureGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TGID))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tgusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tgname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Midtermbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Finalbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(109, 109, 109))
        );

        Studentset.addTab("Grade", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(Studentset)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Studentset))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TsetnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsetnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TsetnameActionPerformed

    private void SaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaddActionPerformed
        // TODO add your handling code here:
            String stdusername=Tsetusername.getText();
            String stdname=Tsetname.getText();
            String stdsurname=Tsetsurname.getText();
            String stdpassworrd=Tspassword.getText();
            String stddate=sdate.getText();
            String stdmnumber=Tsetmnumber.getText();
            String stddepartment = (String) Sdeparrtmentcombo.getSelectedItem();
            String stdfaculty = (String) Sfacultycombo.getSelectedItem();
            String dgender = "Male";
         
         if(sgenderf.isSelected()){
             dgender = "Female";
         }
            
         if(verifyFields())
         {
// check if the username already exists
             if(!checkUsername(stdusername))
             {
                 String registerUserQuery = "INSERT INTO student_info (USERNAME, NAME, SURNAME, PASSWORD, MNUMBER, DEPARTMENT, FACULTY, GENDER, DATE) \n"+"VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
                 try {
                     ps=conn.prepareStatement(registerUserQuery);
                     ps.setString(1, stdusername);
                     ps.setString(2, stdname);
                     ps.setString(3, stdsurname);
                     ps.setString(4, stdpassworrd);
                     ps.setString(5, stdmnumber);
                     ps.setString(6, stddepartment);
                     ps.setString(7, stdfaculty);
                     ps.setString(8, dgender);
                     ps.setString(9, stddate);
                     try{
                          if(ps.executeUpdate()!=0)
                         {
                             JOptionPane.showMessageDialog(null, " Your Account Has Been Created!!");
                         }
                          else{
                             JOptionPane.showMessageDialog(null, "Error Check your information!!");
                         }
                     }
                     catch(SQLException ex){
                         Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
                      
                     }
                     
                     
                 }
                 catch(SQLException ex){
                     Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
                     
                 }
                 }
             
                 
         }
        

    }//GEN-LAST:event_SaddActionPerformed
    public boolean verifyFields(){
        String dname=Tsetname.getText();
        String dsurname=Tsetsurname.getText();
        String dusername=Tsetusername.getText();
        String dpassword=String.valueOf(Tspassword.getPassword());
        String dmnumber=Tsetmnumber.getText();
        String ddate=sdate.getText();
        if (dname.trim().equals("")||dsurname.trim().equals("")||dusername.trim().equals("")||dpassword.trim().equals("")||dmnumber.trim().equals("")||ddate.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Some Fields are Empty");
            return false;
        }
        else{
            return true;
        }
        
    }
        public boolean verifyFieldsLesson(){
        String Lecturename=TSLName.getText();
        String LectureCredi=TSLCredibox.getText();

        if (Lecturename.trim().equals("")||LectureCredi.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Some Fields are Empty");
            return false;
        }
        else{
            return true;
        }
        
    }
    
    private void facultySelect(){
        try{ 
            String sql = "SELECT * FROM faculty";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();

            while (rs.next()){
                String name = rs.getString("Faculty_NAME");
                 Sfacultycombo.addItem(name);
                 TSLFaculty.addItem(name);
                 TGfaculty.addItem(name);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    private void departmentSelect(){
        try{ 

            String sql = "SELECT * FROM department,faculty WHERE Faculty_NAME='"+Sfacultycombo.getSelectedItem()+"'";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            Sdeparrtmentcombo.removeAllItems();
            while (rs.next()){
                String dname = rs.getString("Department_NAME");
                Sdeparrtmentcombo.addItem(dname);
                TSDepartmentcombo.addItem(dname);
                Tgdepartment.addItem(dname);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     private void LectureSelect(){
        try{ 
            String sql = "SELECT * FROM lesson";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery();

            while (rs.next()){
                String name = rs.getString("NAME");
                 LectureGrade.addItem(name);

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
        

        public boolean checkLectureName(String LectureName){
        
        boolean Lecturename_exist=false;
        String query="SELECT * FROM lesson WHERE name=?";
        try{
            ps=conn.prepareStatement(query);
            ps.setString(1,LectureName); 
            rs=ps.executeQuery();
            if(rs.next()){
                Lecturename_exist=true;
                JOptionPane.showMessageDialog(null, "This Lecture is Already", "Lecture error!!", 2);
            }
 
        }
        catch(SQLException ex){
            Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return Lecturename_exist;
    }
       public boolean checkLectureCode(String LectureCode){
        
        boolean LectureCode_exist=false;
        String query="SELECT * FROM lesson WHERE lesson_code=?";
        try{
            ps=conn.prepareStatement(query);
            ps.setString(1,LectureCode); 
            rs=ps.executeQuery();
            if(rs.next()){
                LectureCode_exist=true;
                JOptionPane.showMessageDialog(null, "This Lecture Code is Already", "Lecture Code error!!", 2);
            }
 
        }
        catch(SQLException ex){
            Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return LectureCode_exist;
    }
            
        public boolean checkUsername(String username){
        
        boolean username_exist=false;
        String query="SELECT * FROM student_info WHERE username=?";
        try{
            ps=conn.prepareStatement(query);
            ps.setString(1,username); 
            rs=ps.executeQuery();
            if(rs.next()){
                username_exist=true;
                JOptionPane.showMessageDialog(null, "This Username is Already", "Username error!!", 2);
            }
 
        }
        catch(SQLException ex){
            Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    
    private void sdeletesignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdeletesignupActionPerformed
        // TODO add your handling code here:
        
         try{
           
            stmt=conn.createStatement();
            String DeleteUsername=String.valueOf(TSwaitdelusername.getText());
            String sql="DELETE FROM student_wait WHERE USERNAME='"+DeleteUsername+"'  ";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is Deleting...");
        }      catch (Exception e) {
                   JOptionPane.showMessageDialog(null, e);
               }
        
                                          
    showBekleyen();
    }//GEN-LAST:event_sdeletesignupActionPerformed

    private void TsupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsupdateActionPerformed
        // TODO add your handling code here:
        try{
            stmt=conn.createStatement();
            String SerchUsername=String.valueOf(Tsetusername.getText());
            String stdusername=Tsetusername.getText();
            String stdname=Tsetname.getText();
            String stdsurname=Tsetsurname.getText();
            String stdpassworrd=Tspassword.getText();
            String stddate=sdate.getText();
            String stdmnumber=Tsetmnumber.getText();
            String stddepartment = (String) Sdeparrtmentcombo.getSelectedItem();
            String stdfaculty = (String) Sfacultycombo.getSelectedItem();
            String dgender = "Male";
         
            if(sgenderf.isSelected()){
                dgender = "Female";
                }
            
            String query="UPDATE student_info SET NAME='"+stdname+"',SURNAME='"+stdsurname+"',MNUMBER='"+stdmnumber+"',DEPARTMENT='"+stddepartment+"',FACULTY='"+stdfaculty+"',DATE='"+stddate+"', GENDER='"+dgender+"' WHERE USERNAME='"+stdusername+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Data Update is successfully..");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_TsupdateActionPerformed

    private void TssearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TssearchActionPerformed
        // TODO add your handling code here:
        try{
            stmt=conn.createStatement();
            String SerchUsername=String.valueOf(Tsetusername.getText());
            String sql="SELECT * FROM student_info WHERE USERNAME='"+SerchUsername+"' ";
            rs=stmt.executeQuery(sql);
            if(rs.next()){
                Tsetname.setText(rs.getString("name"));
                Tsetsurname.setText(rs.getString("surname"));
                Tsetusername.setText(rs.getString("username"));
                Tsetmnumber.setText(rs.getString("mnumber"));
                Tspassword.setText(rs.getString("password"));
                sdate.setText(rs.getString("Date"));
                Sfacultycombo.setSelectedItem(rs.getString("faculty"));
                Sdeparrtmentcombo.setSelectedItem(rs.getString("department"));
                String gender=rs.getString("gender");
                if(gender.equals("Male")){
                    sgenderm.setSelected(true);
                     
                }else{
                    sgenderf.setSelected(true);           
                }
                showSearch();
                           
            }else{
                JOptionPane.showMessageDialog(null, "There is no record");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }

        
    }//GEN-LAST:event_TssearchActionPerformed

    private void StudentsettableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentsettableMouseClicked
        // TODO add your handling code here:
        int i=Studentsettable.getSelectedRow();
        TableModel model = Studentsettable.getModel();      
        Tsetname.setText(model.getValueAt(i,2).toString());
        Tsetsurname.setText(model.getValueAt(i,3).toString());
        Tsetusername.setText(model.getValueAt(i,1).toString());
        Tsetmnumber.setText(model.getValueAt(i,5).toString());
        Tspassword.setText(model.getValueAt(i,4).toString());
        Sdeparrtmentcombo.setSelectedItem(model.getValueAt(i,6).toString());
        Sfacultycombo.setSelectedItem(model.getValueAt(i,7).toString());
        sdate.setText(model.getValueAt(i,9).toString());
        String gender=model.getValueAt(i,8).toString();
        if(gender.equals("Male")){
            sgenderm.setSelected(true);
            
            
        }else{
            sgenderf.setSelected(true);
            
        }
        
        
        
        



    }//GEN-LAST:event_StudentsettableMouseClicked

    private void sdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sdateActionPerformed
        // TODO add your handling code here:

            
    }//GEN-LAST:event_sdateActionPerformed

    private void Refresh_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_dataActionPerformed
        // TODO add your handling code here:
        showSet();
        Tsetname.setText(null);
        Tsetsurname.setText(null);
        Tsetusername.setText(null);
        Tsetmnumber.setText(null);
        Tspassword.setText(null);
        Sfacultycombo.setSelectedItem(null);
        Sdeparrtmentcombo.setSelectedItem(null);
        sdate.setText(null);
        
        
    }//GEN-LAST:event_Refresh_dataActionPerformed

    private void StudentWaitingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentWaitingMouseClicked
        // TODO add your handling code here:      
        int i=StudentWaiting.getSelectedRow();
        TableModel model = StudentWaiting.getModel();  
        TSwaitdelusername.setText(model.getValueAt(i,0).toString());
    }//GEN-LAST:event_StudentWaitingMouseClicked

    private void TsdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsdeleteActionPerformed
        // TODO add your handling code here:
          try{
            
        
            stmt=conn.createStatement();
            String DeleteUsername=String.valueOf(Tsetusername.getText());
            String sql="DELETE FROM student_info WHERE USERNAME='"+DeleteUsername+"'  ";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is Deleting...");
            showSet();
        }      catch (Exception e) {
                   JOptionPane.showMessageDialog(null, e);
               }
       
    }//GEN-LAST:event_TsdeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                         String stdusername=TSwaitdelusername.getText();
                         String registerUserQuery = "INSERT INTO student_info (USERNAME, NAME, SURNAME, PASSWORD, MNUMBER, DEPARTMENT, FACULTY, GENDER, DATE) SELECT USERNAME, NAME, SURNAME, PASSWORD, MNUMBER, DEPARTMENT, FACULTY, GENDER, DATE FROM student_wait WHERE username='"+stdusername+"' ";
                 try {   
                     ps=conn.prepareStatement(registerUserQuery);                    
                     try{
                         
                     
                 if(ps.executeUpdate()!=0){
                    String sqldelete="DELETE FROM student_wait WHERE USERNAME='"+stdusername+"'  ";
                    stmt.executeUpdate(sqldelete);
                    showBekleyen();
                 }

                     }catch(SQLException ex){
                         Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
                     }                 
                 }
                 catch(SQLException ex){
                     Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
                 }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddLecctureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLecctureActionPerformed
        // TODO add your handling code here:
            String Lecturename=TSLName.getText();
            String Lecturecredi =String.valueOf(TSLCredibox.getText());
            String Lecturecode=TSCode.getText();
            String LeLessonID=TSLessonID.getText();
            String LeLessonID2=TLessonSpecialID.getText();
            String LessonTID= TeacherID_less.getText();
            
            String stddepartment = (String) TSDepartmentcombo.getSelectedItem();
            String stdfaculty = (String) TSLFaculty.getSelectedItem();         
         if(verifyFieldsLesson())
         {
          if(!checkLectureCode(Lecturecode))
             {
          if(!checkLectureName(Lecturename))
             {
                 String registerUserQuery = "INSERT INTO lesson (ID, NAME, LESSON_CODE, LESSOND_ID, LESSON_CREDI, `LessonT_ID`) VALUES (?, ?, ?, ?, ?,?)";
                 try {
                     ps=conn.prepareStatement(registerUserQuery);
                     ps.setString(1, LeLessonID2);
                     ps.setString(2, Lecturename);
                     ps.setString(3, Lecturecode);
                     ps.setString(5, Lecturecredi);
                     ps.setString(4, LeLessonID);
                     ps.setString(6, LessonTID);


                     try{
                          if(ps.executeUpdate()!=0)
                         {
                             JOptionPane.showMessageDialog(null, " Your Lessons Has Been Added!!");
                         }
                          else{
                             JOptionPane.showMessageDialog(null, "Error Check Lesson!!");
                         }
                     }
                     catch(SQLException ex){
                         Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
                      
                     }
                     
                     
                 }
                 catch(SQLException ex){
                     Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, ex);
                     
                 }
                 
             }
                 
         }}
         showLecture();
    }//GEN-LAST:event_AddLecctureActionPerformed

    private void TSCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSCodeActionPerformed

    private void TSlessonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TSlessonTableMouseClicked
        // TODO add your handling code here:
        int i=TSlessonTable.getSelectedRow();
        TableModel model = TSlessonTable.getModel();      
        TLessonSpecialID.setText(model.getValueAt(i,0).toString());
        TSLName.setText(model.getValueAt(i,1).toString());
        TSLCredibox.setText(model.getValueAt(i,3).toString());
        TSCode.setText(model.getValueAt(i,2).toString());
        TSLessonID.setText(model.getValueAt(i,4).toString());
        TSDepartmentcombo.setSelectedItem(model.getValueAt(i,5).toString());
        TSLFaculty.setSelectedItem(model.getValueAt(i,6).toString());


    }//GEN-LAST:event_TSlessonTableMouseClicked

    private void LecUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecUpdateActionPerformed
        // TODO add your handling code here:
                try{
            stmt=conn.createStatement();
            String Lecturename=TSLName.getText();
            String Lecturecredi =String.valueOf(TSLCredibox.getText());
            String Lecturecode=TSCode.getText();
            String LeLessonID=TSLessonID.getText();
            String LeLessonSpecialID=TLessonSpecialID.getText();

            
            String query="UPDATE lesson SET ID='"+LeLessonSpecialID+"', NAME='"+Lecturename+"',LESSON_CODE='"+Lecturecode+"',LESSOND_ID='"+LeLessonID+"',LESSON_CREDI='"+Lecturecredi+"' WHERE ID='"+LeLessonSpecialID+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Data Update is successfully..");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }showLecture();
    }//GEN-LAST:event_LecUpdateActionPerformed

    private void TSLessonIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSLessonIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TSLessonIDActionPerformed

    private void TlessonsDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TlessonsDeleteActionPerformed
        // TODO add your handling code here:
           try{
           
            stmt=conn.createStatement();
            String DeleteWithID=String.valueOf(TLessonSpecialID.getText());
            String sql="DELETE FROM lesson WHERE ID='"+DeleteWithID+"'  ";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Data is Deleting...");
        }      catch (Exception e) {
                   JOptionPane.showMessageDialog(null, e);
               }
        
                                          
    showLecture();              
    }//GEN-LAST:event_TlessonsDeleteActionPerformed

    private void Refresh_data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_data1ActionPerformed
        // TODO add your handling code here:
        TLessonSpecialID.setText(null);
        TSLName.setText(null);
        TLessonSpecialID.setText(null);
        TSLCredibox.setText(null);
        TSCode.setText(null);
        TSLessonID.setText(null);
        TSLFaculty.setSelectedItem(null);
        TSDepartmentcombo.setSelectedItem(null);
        showLecture();
    }//GEN-LAST:event_Refresh_data1ActionPerformed

    private void SfacultycomboİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SfacultycomboİtemStateChanged
        // TODO add your handling code here:
/*        String s=Sfacultycombo.getSelectedItem().toString();
        String sql="SELECT * FROM department WHERE DepartmentF_ID='"+s+"'";
        try{
            java.sql.PreparedStatement ps=conn.prepareStatement(sql);
            ResultSet rs=ps.executeQuery();
            while(rs.next()){
                Sdeparrtmentcombo.setSelectedItem(rs.getString("Department_NAME"));
                
            }
        }catch(SQLException e){
            Logger.getLogger(Teachers_Panel.class.getName()).log(Level.SEVERE, null, e);
            
        }
  */      
        
        
    }//GEN-LAST:event_SfacultycomboİtemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try{
            stmt=conn.createStatement();
            String SerchUsername=String.valueOf(Tgusername.getText());
            String sql="SELECT * FROM student_info WHERE USERNAME='"+SerchUsername+"' ";
            rs=stmt.executeQuery(sql);
            if(rs.next()){
                Tgname.setText(rs.getString("name"));
                TGID.setText(rs.getString("ID"));
                Tsetusername.setText(rs.getString("username"));
                TGfaculty.setSelectedItem(rs.getString("faculty"));
                Tgdepartment.setSelectedItem(rs.getString("department"));
                showSearch();
                           
            }else{
                JOptionPane.showMessageDialog(null, "There is no record");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TGradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TGradeMouseClicked
        // TODO add your handling code here:
            int i=TGrade.getSelectedRow();
            TableModel model = TGrade.getModel();
            //Tgdepartment.setSelectedItem(model.getValueAt(i,0).toString());
            //TGfaculty.setSelectedItem(model.getValueAt(i,1).toString());
            LectureGrade.setSelectedItem(model.getValueAt(i,1).toString());
            TGID.setText(model.getValueAt(i,2).toString());
            Tgname.setText(model.getValueAt(i,3).toString());
            Tgusername.setText(model.getValueAt(i,5).toString());
            Midtermbox.setText(model.getValueAt(i,6).toString());
            Finalbox.setText(model.getValueAt(i,7).toString());


    }//GEN-LAST:event_TGradeMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try{
            stmt=conn.createStatement();
            String GradeMidterm =String.valueOf(Midtermbox.getText());
            String GradeFinal =String.valueOf(Finalbox.getText());
            String GradestudentSpecialID=TGID.getText();

            
            String query="UPDATE grade SET MIDTERM='"+GradeMidterm+"', FINAL='"+GradeFinal+"' WHERE GRADES_ID='"+GradestudentSpecialID+"'";
            stmt.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Data Update is successfully..");
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }showGrade();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnouncementActionPerformed
        dispose();
        new AnouncementT().setVisible(true);
    }//GEN-LAST:event_AnouncementActionPerformed
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teachers_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teachers_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teachers_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teachers_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teachers_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLeccture;
    private javax.swing.JButton Anouncement;
    private javax.swing.JTextField Finalbox;
    private javax.swing.JButton LecUpdate;
    private javax.swing.JComboBox<String> LectureGrade;
    private javax.swing.JTextField Midtermbox;
    private javax.swing.JToggleButton Refresh_data;
    private javax.swing.JToggleButton Refresh_data1;
    private javax.swing.JButton Sadd;
    private javax.swing.JComboBox<String> Sdeparrtmentcombo;
    private javax.swing.JComboBox<String> Sfacultycombo;
    private javax.swing.JPanel StudentSet;
    private javax.swing.JTable StudentWaiting;
    private javax.swing.JTabbedPane Studentset;
    private javax.swing.JTable Studentsettable;
    private javax.swing.JTextField TGID;
    private javax.swing.JComboBox<String> TGfaculty;
    private javax.swing.JTable TGrade;
    private javax.swing.JTextField TLessonSpecialID;
    private javax.swing.JTextField TSCode;
    private javax.swing.JComboBox<String> TSDepartmentcombo;
    private javax.swing.JTextField TSLCredibox;
    private javax.swing.JComboBox<String> TSLFaculty;
    private javax.swing.JTextField TSLName;
    private javax.swing.JTextField TSLessonID;
    private javax.swing.JTable TSlessonTable;
    private javax.swing.JTextField TSwaitdelusername;
    private javax.swing.JTextField TeacherID_less;
    private javax.swing.JComboBox<String> Tgdepartment;
    private javax.swing.JTextField Tgname;
    private javax.swing.JTextField Tgusername;
    private javax.swing.JButton TlessonsDelete;
    private javax.swing.JToggleButton Tsdelete;
    private javax.swing.JTextField Tsetmnumber;
    private javax.swing.JTextField Tsetname;
    private javax.swing.JTextField Tsetsurname;
    private javax.swing.JTextField Tsetusername;
    private javax.swing.JPasswordField Tspassword;
    private javax.swing.JButton Tssearch;
    private javax.swing.JButton Tsupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel sFacultycombo;
    private javax.swing.JTextField sdate;
    private javax.swing.JButton sdeletesignup;
    private javax.swing.JRadioButton sgenderf;
    private javax.swing.JRadioButton sgenderm;
    // End of variables declaration//GEN-END:variables
}
